about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.about, name='about'),
    path('privacy/', views.privacy, name='privacy.policy'),
    path('purchase/', views.purchaseGuide, name='about.purchase.guide'),
    path('terms/', views.terms, name='about.terms'),
    path('team/', views.team, name='about.team'),
    path('persona/', views.persona, name='about.persona'),
]

blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('post', views.blogPost, name='blog.post'),
]

evara_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('evara_home.urls')),
    path('about/', include('about.urls')),
    path('shop/', include('shop.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blogs.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evara_home/urls.py
from django.urls import path
from django.http import HttpResponse
from . import views

app_name = 'home'
urlpatterns = [
    path('',  views.home, name='home'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.shopGrid, name='shop.main'),
    path('cart/', views.cart, name='shop.cart'),
    path('checkout/', views.checkout, name='shop.checkout'),
    path('compare/', views.compare, name='shop.compare'),
    path('product/', views.product, name='shop.product'),
    path('wishlist', views.wishlist, name='shop.wishlist'),
    path('filter', views.filter, name='shop.filter'),
]

about/models.py
from django.db import models

# Create your models here.

class TeamMember(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='team-member/')
    designation= models.CharField(max_length=255)
    facebook= models.CharField(max_length=255, default='#')
    insta= models.CharField(max_length=255, default='#')
    twitter= models.CharField(max_length=255, default='#')
    status = models.BooleanField(default=True)
    createdat = models.DateTimeField(auto_now_add=True)
    updatedat = models.DateTimeField(auto_now=True)


class Persona(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='personas/')
    organization= models.CharField(max_length=255)
    message = models.CharField(max_length=150)
    status = models.BooleanField(default=True)
    createdat = models.DateTimeField(auto_now_add=True)
    updatedat = models.DateTimeField(auto_now=True)

class MainBranches(models.Model):
    image = models.ImageField(upload_to='team-member/')
    address= models.CharField(max_length=255)
    street= models.CharField(max_length=255)
    postalcode= models.CharField(max_length=255, default='NY 00000, USA')
    status = models.BooleanField(default=True)
    createdat = models.DateTimeField(auto_now_add=True)
    updatedat = models.DateTimeField(auto_now=True)

about/views.py
from django.shortcuts import render
from .models import TeamMember, Persona, MainBranches

def about(request):
    team_members = TeamMember.objects.all()[:4]
    personas = Persona.objects.all()[:6]
    branches = MainBranches.objects.all()[:3]
    return render(request, 'about/about.html', {'team_members':team_members, 'personas': personas, 'branches': branches})

def team(request):
    team_members = TeamMember.objects.all()
    return render(request, 'about/members.html', {'team_members':team_members})

def persona(request):
    personas = Persona.objects.all()
    return render(request, 'about/personas.html', {'personas':personas})

def privacy(request):
    return render(request, 'about/privacy-policy.html')

def purchaseGuide(request):
    return render(request, 'about/purchase-guide.html')

def terms(request):
    return render(request, 'about/terms.html')

about/templates/about/about.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="main single-page">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="{% url 'home:home' %}" rel="nofollow">Home</a>
        <span></span> Pages <span></span> About us
      </div>
    </div>
  </div>
  <section class="section-padding">
    <div class="container pt-25">
      <div class="row">
        <div class="col-lg-6 align-self-center mb-lg-0 mb-4">
          <h6
            class="mt-0 mb-15 text-uppercase font-sm text-brand wow fadeIn animated"
          >
            Our Company
          </h6>
          <h1 class="font-heading mb-40">
            We are Building The Destination For Getting Things Done
          </h1>
          <p>
            Tempus ultricies augue luctus et ut suscipit. Morbi arcu, ultrices
            purus dolor erat bibendum sapien metus.
          </p>
          <p>
            Tempus ultricies augue luctus et ut suscipit. Morbi arcu, ultrices
            purus dolor erat bibendum sapien metus. Sit mi, pharetra, morbi arcu
            id. Pellentesque dapibus nibh augue senectus.
          </p>
        </div>
        <div class="col-lg-6">
          <img src="{% static 'imgs/page/about-1.png' %}" alt="" />
        </div>
      </div>
    </div>
  </section>
  <section id="team" class="pt-25 wow fadeIn animated">
    <div class="container">
      <div class="row mb-50 align-items-center">
        <div class="col-md-6">
          <h6
            class="mt-0 mb-15 text-uppercase font-sm text-brand wow fadeIn animated"
          >
            Our Team
          </h6>
          <h2 class="mb-15 wow fadeIn animated">Top team of experts</h2>
          <p class="text-grey-3 wow fadeIn animated">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione
            optio perferendis sequi mollitia quis autem ea cupiditate possimus!
          </p>
        </div>
        <div class="col-md-6 text-md-end mt-30">
          <a
            href="{% url 'about:about.team' %}"
            class="btn btn-outline btn-lg btn-brand-outline font-weight-bold text-brand text-hover-white border-radius-5 btn-shadow-brand hover-up"
            >All Members</a
          >
        </div>
      </div>
      <div class="position-relative">
        <div class="row wow fadeIn animated">
          {% for member in team_members %}
          <div class="col-lg-3 col-md-6">
            <div class="blog-card border-radius-10 overflow-hidden text-center">
              <img
                src="{{ member.image.url }}"
                alt=""
                class="border-radius-10 mb-30 hover-up"
              />
              <h4 class="fw-500 mb-0">{{member.name}}</h4>
              <p class="fw-400 text-brand mb-10">{{member.designation}}</p>
              <div
                class="mobile-social-icon wow fadeIn animated mb-sm-5 mb-md-0 animated"
              >
                <a href="{{member.facebook}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-facebook.svg' %}"
                    alt=""
                /></a>
                <a href="{{member.twitter}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-twitter.svg' %}"
                    alt=""
                /></a>
                <a href="{{member.insta}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-instagram.svg' %}"
                    alt=""
                /></a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
  <section id="work" class="mt-40 pt-50 pb-50 section-border">
    <div class="container">
      <div class="row mb-50">
        <div class="col-lg-12 col-md-12 text-center">
          <h6
            class="mt-0 mb-5 text-uppercase text-brand font-sm wow fadeIn animated"
          >
            Evara Coporation
          </h6>
          <h2 class="mb-15 text-grey-1 wow fadeIn animated">
            Our main branches<br />
            around the world
          </h2>
          <p class="w-50 m-auto text-grey-3 wow fadeIn animated">
            At vero eos et accusamus et iusto odio dignissimos ducimus
            quiblanditiis praesentium. ebitis nesciunt voluptatum dicta
            reprehenderit accusamus
          </p>
        </div>
      </div>
      <div class="row">
        {% if branches %} {% for branch in branches %}
        <div class="col-md-4 text-center mb-md-0 mb-4">
          <img
            class="btn-shadow-brand hover-up border-radius-10 bg-brand-muted wow fadeIn animated"
            src="{{branch.image.url}}"
            alt=""
          />
          <h4 class="mt-30 mb-15 wow fadeIn animated">{{branch.address}}</h4>
          <p class="text-grey-3 wow fadeIn animated">
            {{branch.street}}<br />{{branch.postalcode}}
          </p>
        </div>
        {% endfor %} {% else %}
        <p class="w-50 m-auto text-grey-3 wow fadeIn animated">
          Branches are not found
        </p>
        {% endif %}
      </div>
    </div>
  </section>
  <section id="testimonials" class="section-padding">
    <div class="container pt-25">
      <div class="row mb-50">
        <div class="col-lg-12 col-md-12 text-center">
          <h6
            class="mt-0 mb-10 text-uppercase text-brand font-sm wow fadeIn animated"
          >
            some facts
          </h6>
          <h2 class="mb-15 text-grey-1 wow fadeIn animated">
            Take a look what<br />
            our clients say about us
          </h2>
          <p class="w-50 m-auto text-grey-3 wow fadeIn animated">
            At vero eos et accusamus et iusto odio dignissimos ducimus
            quiblanditiis praesentium. ebitis nesciunt voluptatum dicta
            reprehenderit accusamus
          </p>
        </div>
      </div>
      <div class="row align-items-center">
        {% for persona in personas %}
        <div class="col-md-6 col-lg-4">
          <div
            class="hero-card box-shadow-outer-6 wow fadeIn animated mb-30 hover-up d-flex"
          >
            <div class="hero-card-icon icon-left-2 hover-up">
              <img
                class="btn-shadow-brand hover-up border-radius-5 bg-brand-muted"
                src="{{persona.image.url}}"
                alt=""
              />
            </div>
            <div class="pl-30">
              <h5 class="mb-5 fw-500">{{persona.name}}</h5>
              <p class="font-sm text-grey-5">{{persona.organiztion}}</p>
              <p class="text-grey-3">"{{persona.message}}"</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="row mt-30">
        <div class="col-12 text-center">
          <p class="wow fadeIn animated">
            <a
              href="{% url 'about:about.persona' %}"
              class="btn btn-brand text-white btn-shadow-brand hover-up btn-lg"
              >View More</a
            >
          </p>
        </div>
      </div>
    </div>
  </section>
  <section class="section-padding">
    <div class="container pb-25">
      <h3 class="section-title mb-20 wow fadeIn animated text-center">
        <span>Featured</span> Clients
      </h3>
      <div
        class="carausel-6-columns-cover position-relative wow fadeIn animated"
      >
        <div class="carausel-6-columns text-center" id="carausel-6-columns-3">
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-1.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-2.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-3.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-4.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-5.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-6.png' %}"
              alt=""
            />
          </div>
          <div class="brand-logo">
            <img
              class="img-grey-hover"
              src="{% static 'imgs/banner/brand-3.png' %}"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

about/templates/about/members.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="main single-page">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="{% url 'home:home' %}" rel="nofollow">Home</a>
        <span></span> About us <span></span> Team members
      </div>
    </div>
  </div>
  <section id="team" class="pt-25 wow fadeIn animated">
    <div class="container">
      <div class="row mb-50 align-items-center">
        <div class="col-md-6">
          <h6
            class="mt-0 mb-15 text-uppercase font-sm text-brand wow fadeIn animated"
          >
            Our Team
          </h6>
          <h2 class="mb-15 wow fadeIn animated">Top team of experts</h2>
          <p class="text-grey-3 wow fadeIn animated">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione
            optio perferendis sequi mollitia quis autem ea cupiditate possimus!
          </p>
        </div>
      </div>
      <div class="position-relative">
        <div class="row wow fadeIn animated mb-20">
          {% for member in team_members %}
          <div class="col-lg-3 col-md-6">
            <div class="blog-card border-radius-10 overflow-hidden text-center">
              <img
                src="{{ member.image.url }}"
                alt=""
                class="border-radius-10 mb-30 hover-up"
              />
              <h4 class="fw-500 mb-0">{{member.name}}</h4>
              <p class="fw-400 text-brand mb-10">{{member.designation}}</p>
              <div
                class="mobile-social-icon wow fadeIn animated mb-sm-5 mb-md-0 animated"
              >
                <a href="{{member.facebook}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-facebook.svg' %}"
                    alt=""
                /></a>
                <a href="{{member.twitter}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-twitter.svg' %}"
                    alt=""
                /></a>
                <a href="{{member.insta}}"
                  ><img
                    src="{% static 'imgs/theme/icons/icon-instagram.svg' %}"
                    alt=""
                /></a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

about/templates/about/purchase-guide.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="main">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="{% url 'home:home' %}" rel="nofollow">Home</a>
        <span></span> Pages <span></span> Purchase Guide
      </div>
    </div>
  </div>
  <section class="mt-50 mb-50">
    <div class="container custom">
      <div class="row">
        <div class="col-lg-9">
          <div class="single-page pr-30 mb-lg-0 mb-sm-5">
            <div class="single-header style-2">
              <h2>Purchase Guide</h2>
              <div class="entry-meta meta-1 font-xs mt-15 mb-15">
                <span class="post-by">By <a href="#">Jonh</a></span>
                <span class="post-on has-dot">9 April 2020</span>
                <span class="time-reading has-dot">8 mins read</span>
                <span class="hit-count has-dot">29k Views</span>
              </div>
            </div>
            <figure class="single-thumbnail">
              <img src="{% static 'assets/imgs/page/img-1.jpg' %}" alt="" />
            </figure>
            <div class="single-content">
              <h4>1. Account Registering</h4>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla
                modi dolores neque omnis ipsa? Quia, nam voluptas! Aut, magnam
                molestias:
              </p>
              <ul class="mb-30">
                <li>Name (required)</li>
                <li>Age (required)</li>
                <li>Date of birth (required)</li>
                <li>Passport/ ID no. (required)</li>
                <li>Current career (required)</li>
                <li>Mobile phone numbers (required)</li>
                <li>Email address (required)</li>
                <li>Hobbies &amp; interests (optional)</li>
                <li>Social profiles (optional)</li>
              </ul>
              <h4>2. Select Product</h4>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Suscipit officia necessitatibus repellat placeat aut enim
                recusandae assumenda adipisci quisquam, deserunt iure veritatis
                cupiditate modi aspernatur accusantium, mollitia doloribus.
                Velit, iste.
              </p>
              <h4>3. Confirm Order Content</h4>
              <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero
                ut autem sed! Assumenda, nostrum non doloribus tenetur, pariatur
                veritatis harum natus ipsam maiores dolorem repudiandae
                laboriosam, cupiditate odio earum eum?
              </p>
              <h4>4.Transaction Completed</h4>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam
                nesciunt nam aut magnam libero aspernatur eaque praesentium?
                Tempore labore quis neque? Magni.
              </p>
              <h4>5. Accepted Credit Cards</h4>
              <ul>
                <li>Visa</li>
                <li>Mastercards</li>
                <li>American Express</li>
                <li>Discover</li>
              </ul>
              <span
                >*Taxes are calculated by your local bank and location.</span
              >
              <h4 class="mt-30">6. Download and Setup</h4>
              <ul>
                <li>Updated content on a regular basis</li>
                <li>Secure &amp; hassle-free payment</li>
                <li>1-click checkout</li>
                <li>Easy access &amp; smart user dashboard</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-3 primary-sidebar sticky-sidebar">
          <div class="widget-area">
            <div class="sidebar-widget widget_search mb-50">
              <div class="search-form">
                <form action="#">
                  <input type="text" placeholder="Search…" />
                  <button type="submit"><i class="fi-rs-search"></i></button>
                </form>
              </div>
            </div>
            <!--Widget categories-->
            <div class="sidebar-widget widget_categories mb-40">
              <div class="widget-header position-relative mb-20 pb-10">
                <h5 class="widget-title">Categories</h5>
              </div>
              <div class="post-block-list post-module-1 post-module-5">
                <ul>
                  <li class="cat-item cat-item-2">
                    <a href="{% url 'blogs:blogs' %}">Beauty</a> (3)
                  </li>
                  <li class="cat-item cat-item-3">
                    <a href="{% url 'blogs:blogs' %}">Book</a> (6)
                  </li>
                  <li class="cat-item cat-item-4">
                    <a href="{% url 'blogs:blogs' %}">Design</a> (4)
                  </li>
                  <li class="cat-item cat-item-5">
                    <a href="{% url 'blogs:blogs' %}">Fashion</a> (3)
                  </li>
                  <li class="cat-item cat-item-6">
                    <a href="{% url 'blogs:blogs' %}">Lifestyle</a> (6)
                  </li>
                  <li class="cat-item cat-item-7">
                    <a href="{% url 'blogs:blogs' %}">Travel</a> (2)
                  </li>
                </ul>
              </div>
            </div>
            <!--Widget latest posts style 1-->
            <div class="sidebar-widget widget_alitheme_lastpost mb-20">
              <div class="widget-header position-relative mb-20 pb-10">
                <h5 class="widget-title">Trending Now</h5>
              </div>
              <div class="row">
                <div class="col-12 sm-grid-content mb-30">
                  <div
                    class="post-thumb d-flex border-radius-5 img-hover-scale mb-15"
                  >
                    <a href="{% url 'blogs:blog.post' %}">
                      <img
                        src="{% static 'assets/imgs/blog/blog-1.jpg' %}"
                        alt=""
                      />
                    </a>
                  </div>
                  <div class="post-content media-body">
                    <h4 class="post-title mb-10 text-limit-2-row">
                      The litigants on the screen are not actors
                    </h4>
                    <div class="entry-meta meta-13 font-xxs color-grey">
                      <span class="post-on mr-10">25 April</span>
                      <span class="hit-count has-dot">126k Views</span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 col-sm-6 sm-grid-content mb-30">
                  <div
                    class="post-thumb d-flex border-radius-5 img-hover-scale mb-15"
                  >
                    <a href="{% url 'blogs:blog.post' %}">
                      <img
                        src="{% static 'assets/imgs/blog/blog-3.jpg' %}"
                        alt=""
                      />
                    </a>
                  </div>
                  <div class="post-content media-body">
                    <h6 class="post-title mb-10 text-limit-2-row">
                      Water Partners With Rag &amp; Bone To Consume
                    </h6>
                    <div class="entry-meta meta-13 font-xxs color-grey">
                      <span class="post-on mr-10">25 April</span>
                      <span class="hit-count has-dot">126k Views</span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 col-sm-6 sm-grid-content mb-30">
                  <div
                    class="post-thumb d-flex border-radius-5 img-hover-scale mb-15"
                  >
                    <a href="{% url 'blogs:blog.post' %}">
                      <img
                        src="{% static 'assets/imgs/blog/blog-4.jpg' %}"
                        alt=""
                      />
                    </a>
                  </div>
                  <div class="post-content media-body">
                    <h6 class="post-title mb-10 text-limit-2-row">
                      The loss is not all that surprising
                    </h6>
                    <div class="entry-meta meta-13 font-xxs color-grey">
                      <span class="post-on mr-10">25 April</span>
                      <span class="hit-count has-dot">126k Views</span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 col-sm-6 sm-grid-content mb-30">
                  <div
                    class="post-thumb d-flex border-radius-5 img-hover-scale mb-15"
                  >
                    <a href="{% url 'blogs:blog.post' %}">
                      <img
                        src="{% static 'assets/imgs/blog/blog-5.jpg' %}"
                        alt=""
                      />
                    </a>
                  </div>
                  <div class="post-content media-body">
                    <h6 class="post-title mb-10 text-limit-2-row">
                      We got a right to pick a little fight, Bonanza
                    </h6>
                    <div class="entry-meta meta-13 font-xxs color-grey">
                      <span class="post-on mr-10">25 April</span>
                      <span class="hit-count has-dot">126k Views</span>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 col-sm-6 sm-grid-content mb-30">
                  <div
                    class="post-thumb d-flex border-radius-5 img-hover-scale mb-15"
                  >
                    <a href="{% url 'blogs:blog.post' %}">
                      <img
                        src="{% static 'assets/imgs/blog/blog-6.jpg' %}"
                        alt=""
                      />
                    </a>
                  </div>
                  <div class="post-content media-body">
                    <h6 class="post-title mb-10 text-limit-2-row">
                      My entrance exam was on a book of matches
                    </h6>
                    <div class="entry-meta meta-13 font-xxs color-grey">
                      <span class="post-on mr-10">25 April</span>
                      <span class="hit-count has-dot">126k Views</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!--Widget ads-->
            <div
              class="banner-img wow fadeIn mb-45 animated d-lg-block d-none animated"
            >
              <img
                src="{% static 'assets/imgs/banner/banner-11.jpg' %}"
                alt=""
              />
              <div class="banner-text">
                <span>Women Zone</span>
                <h4>Save 17% on <br />Office Dress</h4>
                <a href="{% url 'shop:shop.main' %}"
                  >Shop Now <i class="fi-rs-arrow-right"></i
                ></a>
              </div>
            </div>
            <!--Widget Tags-->
            <div class="sidebar-widget widget_tags mb-50">
              <div class="widget-header position-relative mb-20 pb-10">
                <h5 class="widget-title">Popular tags</h5>
              </div>
              <div class="tagcloud">
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >beautiful</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >New York</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >droll</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >intimate</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >loving</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >travel</a
                >
                <a class="tag-cloud-link" href="{% url 'blogs:blogs' %}"
                  >fighting
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}