contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact')
]

evara_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('evara_home.urls')),
    path('about/', include('about.urls')),
    path('shop/', include('shop.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blogs.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.shopGrid, name='shop.main'),
    path('cart/', views.cart, name='shop.cart'),
    path('checkout/', views.checkout, name='shop.checkout'),
    path('compare/', views.compare, name='shop.compare'),
    path('product/', views.product, name='shop.product'),
    path('wishlist', views.wishlist, name='shop.wishlist'),
    path('filter', views.filter, name='shop.filter'),
]

contact/models.py
from django.db import models

# Create your models here.

class ContactUs(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField(max_length=255)
    contact = models.CharField(max_length=15)
    subject = models.CharField(max_length=250)
    accesstoken = models.CharField(max_length=250)
    message = models.TextField()
    createdat = models.DateTimeField(auto_now_add=True)
    updatedat = models.DateTimeField(auto_now=True)

contact/forms.py
from django import forms
from .models import ContactUs

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name','email','contact','subject','message', 'accesstoken']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Your Email'}),
            'contact': forms.TextInput(attrs={'placeholder': 'Your Phone'}),
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Message'}),
        }

contact/views.py
from django.shortcuts import render
from .models import ContactUs
from .forms import ContactForm
from uuid import uuid4

def contact(request):
    # if request.method == 'POST':
    #     name = request.POST['name']
    #     email = request.POST['email']
    #     telephone = request.POST['telephone']
    #     subject = request.POST['subject']
    #     message = request.POST['message']
    #     accesstoken = request.POST['csrfmiddlewaretoken']
        
    #     contact_us = ContactUs(name=name, email=email, contact=telephone, subject=subject, message=message, accesstoken=accesstoken)
    #     contact_us.save()
    custom_token_value = uuid4()
    if request.method == 'POST':
        filled_form = ContactForm(request.POST)
        if filled_form.is_valid():
            note = 'Thanks for contact us,'
            filled_form.save()
            new_form = ContactForm(initial={'accesstoken': custom_token_value})  
            return render(request, 'contact/contact.html', {'ContactFrom': new_form, 'note':note})
    else:
        form = ContactForm(initial={'accesstoken': custom_token_value})  
        return render(request, 'contact/contact.html', {'ContactFrom':form})

contact/templates/contact/contact.html
{% extends "base.html" %} {% block content %}{% load static %}
<main class="main">
  <div class="page-header breadcrumb-wrap">
    <div class="container">
      <div class="breadcrumb">
        <a href="index.html" rel="nofollow">Home</a>
        <span></span> Pages <span></span> Contact us
      </div>
    </div>
  </div>
  <section class="hero-2 bg-green">
    <div class="hero-content">
      <div class="container">
        <div class="text-center">
          <h4 class="text-brand mb-20">Get in touch</h4>
          <h1 class="mb-20 wow fadeIn animated font-xxl fw-900">
            Let's Talk About <br />Your <span class="text-style-1">Idea</span>
          </h1>
          <p class="w-50 m-auto mb-50 wow fadeIn animated">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum quam
            eius placeat, a quidem mollitia at accusantium reprehenderit
            pariatur provident nam ratione incidunt magnam sequi.
          </p>
          <p class="wow fadeIn animated">
            <a
              class="btn btn-brand btn-lg font-weight-bold text-white border-radius-5 btn-shadow-brand hover-up"
              href="page-about.html"
              >About Us</a
            >
            <a
              class="btn btn-outline btn-lg btn-brand-outline font-weight-bold text-brand bg-white text-hover-white ml-15 border-radius-5 btn-shadow-brand hover-up"
              >Support Center</a
            >
          </p>
        </div>
      </div>
    </div>
  </section>
  <section class="pt-50 pb-50">
    <div class="container">
      <div class="row">
        <div class="col-xl-8 col-lg-10 m-auto">
          <div class="contact-from-area padding-20-row-col wow FadeInUp">
            <h3 class="mb-10 text-center">Drop Us a Line</h3>
            <p class="text-muted mb-30 text-center font-sm">
              Lorem ipsum dolor sit amet consectetur.
            </p>
            <form
              class="contact-form-style text-center"
              id="contact-form"
              method="post"
              action="{% url 'contact:contact' %}"
            >
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-6 col-md-6">
                  <div class="input-style mb-20">{{ContactFrom.name}}</div>
                </div>
                <div class="col-lg-6 col-md-6">
                  <div class="input-style mb-20">{{ContactFrom.email}}</div>
                </div>
                <div class="col-lg-6 col-md-6">
                  <div class="input-style mb-20">{{ContactFrom.contact}}</div>
                </div>
                <div class="col-lg-6 col-md-6">
                  <div class="input-style mb-20">{{ContactFrom.subject}}</div>
                </div>
                <div class="col-lg-12 col-md-12">
                  <div class="textarea-style mb-30">
                    {{ContactFrom.message}}
                  </div>
                  <div style="display: none">{{ContactFrom.accesstoken}}</div>
                  <button class="submit submit-auto-width" type="submit">
                    Send message
                  </button>
                </div>
                {{note}}
              </div>
            </form>
            <p class="form-messege"></p>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}